---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts/{post_id}/comments":
    get:
      summary: List of comments for a particular user
      tags:
      - Comments
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
      - name: user_id
        in: path
        type: integer
        required: true
      - name: post_id
        in: path
        type: integer
        required: true
      security:
      - JWT: {}
      responses:
        '200':
          description: Comments list
        '401':
          description: Unauthorized
  "/api/v1/users/posts/commentonpost":
    post:
      summary: user comment on a particular post, ensure to add token as Authorization
        header
      tags:
      - Post Comment
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
      - name: params
        in: body
        schema:
          type: object
          properties:
            text:
              type: string
            post_id:
              type: integer
          required:
          - post_id
          - text
      security:
      - JWT: {}
      responses:
        '200':
          description: Post user comment, ensure to add token as Authorization header
        '404':
          description: post not found
  "/api/v1/users/{user_id}/posts":
    get:
      summary: List of posts for a particular user
      tags:
      - Posts
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
      - name: user_id
        in: path
        type: integer
        required: true
      security:
      - JWT: {}
      responses:
        '200':
          description: Posts list
        '401':
          description: Unauthorized
  "/api/v1/users/login":
    post:
      summary: Authentication to get jwt token
      tags:
      - User
      consumes:
      - application/json
      parameters:
      - name: params
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: Login Successful
        '401':
          description: Unauthorized
  "/api/v1/users":
    get:
      summary: List of all users, ensure to add token as Authorization header
      tags:
      - User
      produces:
      - application/json
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        type: string
      responses:
        '200':
          description: Users list
        '401':
          description: Users list
  "/api/v1/users/signup":
    post:
      summary: Register a new user
      tags:
      - User Registration
      consumes:
      - application/json
      parameters:
      - name: params
        in: body
        schema:
          type: object
          properties:
            Name:
              type: string
            email:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
            Bio:
              type: string
            confirmed_at:
              type: string
            Photo:
              type: string
            role:
              type: string
          required:
          - Name
          - email
          - password
          - password_confirmation
          - Bio
          - confirmed_at
          - Photo
          - role
      responses:
        '200':
          description: User created
        '401':
          description: Invalid request
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
securityDefinitions:
  JWT:
    description: the jwt for API auth
    type: apiKey
    name: Authorization
    in: header
